//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4216
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mbe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mbeboardfont.dat")]
        public string PathBoardFont {
            get {
                return ((string)(this["PathBoardFont"]));
            }
            set {
                this["PathBoardFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseEmbeddedFont {
            get {
                return ((bool)(this["UseEmbeddedFont"]));
            }
            set {
                this["UseEmbeddedFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPTH {
            get {
                return ((uint)(this["CustomColorPTH"]));
            }
            set {
                this["CustomColorPTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPLC {
            get {
                return ((uint)(this["CustomColorPLC"]));
            }
            set {
                this["CustomColorPLC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorSTC {
            get {
                return ((uint)(this["CustomColorSTC"]));
            }
            set {
                this["CustomColorSTC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorCMP {
            get {
                return ((uint)(this["CustomColorCMP"]));
            }
            set {
                this["CustomColorCMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorSOL {
            get {
                return ((uint)(this["CustomColorSOL"]));
            }
            set {
                this["CustomColorSOL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorSTS {
            get {
                return ((uint)(this["CustomColorSTS"]));
            }
            set {
                this["CustomColorSTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPLS {
            get {
                return ((uint)(this["CustomColorPLS"]));
            }
            set {
                this["CustomColorPLS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorDIM {
            get {
                return ((uint)(this["CustomColorDIM"]));
            }
            set {
                this["CustomColorDIM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorDRL {
            get {
                return ((uint)(this["CustomColorDRL"]));
            }
            set {
                this["CustomColorDRL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorDOC {
            get {
                return ((uint)(this["CustomColorDOC"]));
            }
            set {
                this["CustomColorDOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GridPitch {
            get {
                return ((int)(this["GridPitch"]));
            }
            set {
                this["GridPitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GridDisplayEvery {
            get {
                return ((int)(this["GridDisplayEvery"]));
            }
            set {
                this["GridDisplayEvery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int DrcPatternGap {
            get {
                return ((int)(this["DrcPatternGap"]));
            }
            set {
                this["DrcPatternGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DrcErrorCheckLimit {
            get {
                return ((int)(this["DrcErrorCheckLimit"]));
            }
            set {
                this["DrcErrorCheckLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorOriginMark {
            get {
                return ((uint)(this["CustomColorOriginMark"]));
            }
            set {
                this["CustomColorOriginMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorGridOrigin {
            get {
                return ((uint)(this["CustomColorGridOrigin"]));
            }
            set {
                this["CustomColorGridOrigin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorGrid {
            get {
                return ((uint)(this["CustomColorGrid"]));
            }
            set {
                this["CustomColorGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorSnapMark {
            get {
                return ((uint)(this["CustomColorSnapMark"]));
            }
            set {
                this["CustomColorSnapMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPinNum {
            get {
                return ((uint)(this["CustomColorPinNum"]));
            }
            set {
                this["CustomColorPinNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorCursor {
            get {
                return ((uint)(this["CustomColorCursor"]));
            }
            set {
                this["CustomColorCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorBgOutside {
            get {
                return ((uint)(this["CustomColorBgOutside"]));
            }
            set {
                this["CustomColorBgOutside"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorInputErr {
            get {
                return ((uint)(this["CustomColorInputErr"]));
            }
            set {
                this["CustomColorInputErr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowState {
            get {
                return ((int)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int MainWindowWidth {
            get {
                return ((int)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public int MainWindowHeight {
            get {
                return ((int)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PrintLeftMargin {
            get {
                return ((int)(this["PrintLeftMargin"]));
            }
            set {
                this["PrintLeftMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PrintBottomMargin {
            get {
                return ((int)(this["PrintBottomMargin"]));
            }
            set {
                this["PrintBottomMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExpBmpLeft {
            get {
                return ((int)(this["ExpBmpLeft"]));
            }
            set {
                this["ExpBmpLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExpBmpBottom {
            get {
                return ((int)(this["ExpBmpBottom"]));
            }
            set {
                this["ExpBmpBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000000")]
        public int ExpBmpWidth {
            get {
                return ((int)(this["ExpBmpWidth"]));
            }
            set {
                this["ExpBmpWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000000")]
        public int ExpBmpHeight {
            get {
                return ((int)(this["ExpBmpHeight"]));
            }
            set {
                this["ExpBmpHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ExpBmpResolution {
            get {
                return ((int)(this["ExpBmpResolution"]));
            }
            set {
                this["ExpBmpResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorActiveSnapMark {
            get {
                return ((uint)(this["CustomColorActiveSnapMark"]));
            }
            set {
                this["CustomColorActiveSnapMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorBg {
            get {
                return ((uint)(this["CustomColorBg"]));
            }
            set {
                this["CustomColorBg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultGridInfoString {
            get {
                return ((string)(this["DefaultGridInfoString"]));
            }
            set {
                this["DefaultGridInfoString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyStandardGridString {
            get {
                return ((string)(this["MyStandardGridString"]));
            }
            set {
                this["MyStandardGridString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyStandardLineString {
            get {
                return ((string)(this["MyStandardLineString"]));
            }
            set {
                this["MyStandardLineString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyStandardHoleString {
            get {
                return ((string)(this["MyStandardHoleString"]));
            }
            set {
                this["MyStandardHoleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyStandardPthString {
            get {
                return ((string)(this["MyStandardPthString"]));
            }
            set {
                this["MyStandardPthString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyStandardPadString {
            get {
                return ((string)(this["MyStandardPadString"]));
            }
            set {
                this["MyStandardPadString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyStandardArcString {
            get {
                return ((string)(this["MyStandardArcString"]));
            }
            set {
                this["MyStandardArcString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyStandardTextString {
            get {
                return ((string)(this["MyStandardTextString"]));
            }
            set {
                this["MyStandardTextString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyStandardPolygonString {
            get {
                return ((string)(this["MyStandardPolygonString"]));
            }
            set {
                this["MyStandardPolygonString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorL2 {
            get {
                return ((uint)(this["CustomColorL2"]));
            }
            set {
                this["CustomColorL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorL3 {
            get {
                return ((uint)(this["CustomColorL3"]));
            }
            set {
                this["CustomColorL3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorMMC {
            get {
                return ((uint)(this["CustomColorMMC"]));
            }
            set {
                this["CustomColorMMC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorMMS {
            get {
                return ((uint)(this["CustomColorMMS"]));
            }
            set {
                this["CustomColorMMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18446744073709551615")]
        public ulong GerberExportLayer {
            get {
                return ((ulong)(this["GerberExportLayer"]));
            }
            set {
                this["GerberExportLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyStandardLibString {
            get {
                return ((string)(this["MyStandardLibString"]));
            }
            set {
                this["MyStandardLibString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("toolMark.mb3")]
        public string ToolMarkFile {
            get {
                return ((string)(this["ToolMarkFile"]));
            }
            set {
                this["ToolMarkFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Print2xMode {
            get {
                return ((bool)(this["Print2xMode"]));
            }
            set {
                this["Print2xMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CenterPunchMode {
            get {
                return ((bool)(this["CenterPunchMode"]));
            }
            set {
                this["CenterPunchMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ToolMarkPrint {
            get {
                return ((bool)(this["ToolMarkPrint"]));
            }
            set {
                this["ToolMarkPrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyStandardPrintPageLayerString {
            get {
                return ((string)(this["MyStandardPrintPageLayerString"]));
            }
            set {
                this["MyStandardPrintPageLayerString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintCurrentView {
            get {
                return ((bool)(this["PrintCurrentView"]));
            }
            set {
                this["PrintCurrentView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintPTH {
            get {
                return ((uint)(this["CustomColorPrintPTH"]));
            }
            set {
                this["CustomColorPrintPTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintPLC {
            get {
                return ((uint)(this["CustomColorPrintPLC"]));
            }
            set {
                this["CustomColorPrintPLC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintSTC {
            get {
                return ((uint)(this["CustomColorPrintSTC"]));
            }
            set {
                this["CustomColorPrintSTC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintCMP {
            get {
                return ((uint)(this["CustomColorPrintCMP"]));
            }
            set {
                this["CustomColorPrintCMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintSOL {
            get {
                return ((uint)(this["CustomColorPrintSOL"]));
            }
            set {
                this["CustomColorPrintSOL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintSTS {
            get {
                return ((uint)(this["CustomColorPrintSTS"]));
            }
            set {
                this["CustomColorPrintSTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintPLS {
            get {
                return ((uint)(this["CustomColorPrintPLS"]));
            }
            set {
                this["CustomColorPrintPLS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintDIM {
            get {
                return ((uint)(this["CustomColorPrintDIM"]));
            }
            set {
                this["CustomColorPrintDIM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintDRL {
            get {
                return ((uint)(this["CustomColorPrintDRL"]));
            }
            set {
                this["CustomColorPrintDRL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintDOC {
            get {
                return ((uint)(this["CustomColorPrintDOC"]));
            }
            set {
                this["CustomColorPrintDOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintL2 {
            get {
                return ((uint)(this["CustomColorPrintL2"]));
            }
            set {
                this["CustomColorPrintL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintL3 {
            get {
                return ((uint)(this["CustomColorPrintL3"]));
            }
            set {
                this["CustomColorPrintL3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintMMC {
            get {
                return ((uint)(this["CustomColorPrintMMC"]));
            }
            set {
                this["CustomColorPrintMMC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint CustomColorPrintMMS {
            get {
                return ((uint)(this["CustomColorPrintMMS"]));
            }
            set {
                this["CustomColorPrintMMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint PrintColorMode {
            get {
                return ((uint)(this["PrintColorMode"]));
            }
            set {
                this["PrintColorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImageColorMode {
            get {
                return ((bool)(this["ImageColorMode"]));
            }
            set {
                this["ImageColorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainTitleText {
            get {
                return ((string)(this["MainTitleText"]));
            }
            set {
                this["MainTitleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ListFileUseLocalEncoding {
            get {
                return ((int)(this["ListFileUseLocalEncoding"]));
            }
            set {
                this["ListFileUseLocalEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrintHeader {
            get {
                return ((bool)(this["PrintHeader"]));
            }
            set {
                this["PrintHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeaderText {
            get {
                return ((string)(this["HeaderText"]));
            }
            set {
                this["HeaderText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ForceClipboardTextFormat {
            get {
                return ((int)(this["ForceClipboardTextFormat"]));
            }
            set {
                this["ForceClipboardTextFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrintMirrorMode {
            get {
                return ((bool)(this["PrintMirrorMode"]));
            }
            set {
                this["PrintMirrorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint PasteObjectAtCursor {
            get {
                return ((uint)(this["PasteObjectAtCursor"]));
            }
            set {
                this["PasteObjectAtCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyEditFlip {
            get {
                return ((string)(this["SCKeyEditFlip"]));
            }
            set {
                this["SCKeyEditFlip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyEditComponenting {
            get {
                return ((string)(this["SCKeyEditComponenting"]));
            }
            set {
                this["SCKeyEditComponenting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyEditUncomponenting {
            get {
                return ((string)(this["SCKeyEditUncomponenting"]));
            }
            set {
                this["SCKeyEditUncomponenting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyEditProperty {
            get {
                return ((string)(this["SCKeyEditProperty"]));
            }
            set {
                this["SCKeyEditProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyUpdateFillPolygon {
            get {
                return ((string)(this["SCKeyUpdateFillPolygon"]));
            }
            set {
                this["SCKeyUpdateFillPolygon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyViewPolygonFrameMode {
            get {
                return ((string)(this["SCKeyViewPolygonFrameMode"]));
            }
            set {
                this["SCKeyViewPolygonFrameMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyToolSelector {
            get {
                return ((string)(this["SCKeyToolSelector"]));
            }
            set {
                this["SCKeyToolSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyToolConnectionCheck {
            get {
                return ((string)(this["SCKeyToolConnectionCheck"]));
            }
            set {
                this["SCKeyToolConnectionCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyToolMeasure {
            get {
                return ((string)(this["SCKeyToolMeasure"]));
            }
            set {
                this["SCKeyToolMeasure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyToolHole {
            get {
                return ((string)(this["SCKeyToolHole"]));
            }
            set {
                this["SCKeyToolHole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyToolPTH {
            get {
                return ((string)(this["SCKeyToolPTH"]));
            }
            set {
                this["SCKeyToolPTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyToolPad {
            get {
                return ((string)(this["SCKeyToolPad"]));
            }
            set {
                this["SCKeyToolPad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyToolLine {
            get {
                return ((string)(this["SCKeyToolLine"]));
            }
            set {
                this["SCKeyToolLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyToolArc {
            get {
                return ((string)(this["SCKeyToolArc"]));
            }
            set {
                this["SCKeyToolArc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyToolText {
            get {
                return ((string)(this["SCKeyToolText"]));
            }
            set {
                this["SCKeyToolText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyToolPolygon {
            get {
                return ((string)(this["SCKeyToolPolygon"]));
            }
            set {
                this["SCKeyToolPolygon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyToolComponent {
            get {
                return ((string)(this["SCKeyToolComponent"]));
            }
            set {
                this["SCKeyToolComponent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeySetGridOrigin {
            get {
                return ((string)(this["SCKeySetGridOrigin"]));
            }
            set {
                this["SCKeySetGridOrigin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyResetGridOrigin {
            get {
                return ((string)(this["SCKeyResetGridOrigin"]));
            }
            set {
                this["SCKeyResetGridOrigin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OneKeyToolSelection {
            get {
                return ((int)(this["OneKeyToolSelection"]));
            }
            set {
                this["OneKeyToolSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyEditBulkHole {
            get {
                return ((string)(this["SCKeyEditBulkHole"]));
            }
            set {
                this["SCKeyEditBulkHole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyEditBulkPTH {
            get {
                return ((string)(this["SCKeyEditBulkPTH"]));
            }
            set {
                this["SCKeyEditBulkPTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyEditBulkPad {
            get {
                return ((string)(this["SCKeyEditBulkPad"]));
            }
            set {
                this["SCKeyEditBulkPad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyEditBulkLine {
            get {
                return ((string)(this["SCKeyEditBulkLine"]));
            }
            set {
                this["SCKeyEditBulkLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyEditBulkText {
            get {
                return ((string)(this["SCKeyEditBulkText"]));
            }
            set {
                this["SCKeyEditBulkText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyEditBulkPolygon {
            get {
                return ((string)(this["SCKeyEditBulkPolygon"]));
            }
            set {
                this["SCKeyEditBulkPolygon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string SCKeyEditBulkLayer {
            get {
                return ((string)(this["SCKeyEditBulkLayer"]));
            }
            set {
                this["SCKeyEditBulkLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InhibitHatchBrushPolygonframe {
            get {
                return ((int)(this["InhibitHatchBrushPolygonframe"]));
            }
            set {
                this["InhibitHatchBrushPolygonframe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DrawTextSolidly {
            get {
                return ((int)(this["DrawTextSolidly"]));
            }
            set {
                this["DrawTextSolidly"] = value;
            }
        }
    }
}
